kumpul remedi
Djulizah/LABBD23 pull request #35
Opened 2023-12-05 10:53 UTC by muh-iswari

2023-12-05 15:50 UTC, Djulizah requested changes

2023-12-05 15:50 UTC, Djulizah commented on H071221007/Remedial/Remedial.sql
> +('ayaka', 0, 7, 1);
`isBuild` -> `boolean`, boolean isinya memang bisa 1/0 secara umum tapi disini bakal error kecuali pakai BIT atau TINYINT, jadi diganti ke value yang sesuai ya, atau kalo memang sy salah balas aja komennya dg bukti 🖊️

2023-12-05 15:50 UTC, Djulizah commented on H071221007/Remedial/Remedial.sql
> +    customer c ON py.customer_id = c.customer_id
kalau saya nda pakai customer, justru dsini ada `subquery`  -> total rental yang tiap pelanggan melakukan pembayaran

2023-12-06 02:25 UTC, muh-iswari commented on H071221007/Remedial/Remedial.sql
> +('ayaka', 0, 7, 1);
siap kak

2023-12-06 11:54 UTC, merged